let title = document.querySelector(".card")
title.style.width = "600px"
title.style.height = "700px"
title.style.background = "black"
title.style.marginLeft = "450px"
title.style.borderRadius = "20px"
let img = document.querySelector("img")
img.style.width = ("230px")
img.style.borderRadius = ("50%")
img.style.marginLeft = ("180px")
img.style.marginTop = ("30px")
let holl = document.querySelector("h1")
holl.style.textDecoration = ("none")
holl.style.color = ("White")
holl.style.marginLeft = ("210px")
let ash = document.querySelector("h3")
ash.style.marginLeft = ("240px")
ash.style.color = ("white")
let kid = document.querySelector("span")
kid.style.marginLeft = "30px"
let tal = document.querySelector(".about")
tal.style.display = "flex"
tal.style.alignItems = "center"
tal.style.justifyContent = "space-around"
let dj= document.querySelector(".about h1")
dj.style.color = "White"
let bish = document.querySelector(".about h2")
bish.style.color = "white"
bish.style.fontSize = "32px"
let bat = document.querySelector(".about h2 span")
bat.style.marginLeft = "55px"
let chuy = document.querySelector(".about h3 span")
chuy.style.marginLeft = "55px"
let osh = document.querySelector(".about h3")
osh.style.color = "white"
osh.style.fontSize = "32px"
let lemon = document.querySelector(".card button")
lemon.style.background = "White"
lemon.style.border = "none"
lemon.style.marginLeft = "60px"
lemon.style.width = "140px"
lemon.style.height = "50px"
lemon.style.cursor = "pointer"
lemon.style.borderRadius = "10px"
let moon = document.querySelector(".card button a")
moon.style.textDecoration = "none"
moon.style.color = "black"
let wh = document.querySelector(".block a ion-icon")
wh.style.fontSize= "40px"
wh.style.color = "white"
wh.style.marginTop = "5px"
let klaus = document.querySelector(".block")
klaus.style.display = "flex"
klaus.style.alignItems = "center"
klaus.style.gap = "33px"
klaus.style.color = "red"
let you = document.querySelector(".git ion-icon")
you.style.fontSize = "40px"
you.style.color = "white"
let git = document.querySelector(".youtb ion-icon")
git.style.fontSize = "40px"
git.style.color = "white"
let loc = document.querySelector(".located ion-icon")
loc.style.color = "white"
loc.style.fontSize = "40px"

